<div class="main-page">
<legend>Welcome on administration site!</legend>


    <div class="info">
<div class="warning"><img src="/img/alert.png" align="left">
<h3>Important information</h3>
<p>Follow this <a href="/help">link</a> to get acquainted with the basic features of the site.</p>
<p><a href="/change">See recent changes</a></p>
    </div>
<hr>
    <div class="info"><img src="/img/change.png" align="left">
    <h3>NEWS</h3>
    <h4> Revised</h4>
    <ol>
        <li>You can create methods for another projects.</li>
        <li>Improved site structure.</li>
        <li>Improved methods of adding.</li>
    </ol>
        </div>
<hr>
    <div class="well pull-left" style="min-width: 340px; margin: 5px; padding: 8px 0;">
    <ul class="nav nav-list">
        <li class="nav-header">Our project</li>
        <?php foreach ($this->project as $project){ ?>
        <li ><a href="/method/index/project/<?=$project['id']?>"><?=$project['name']?></a></li>
        <?php }?>
    </ul></div>
</div>