<div class="main-page">
<legend>Welcome on administration site!</legend>
<div class="warning"><img src="/img/alert.png" align="left">
<h3>Important information</h3>
<p>Follow this <a href="/help">link</a> to get acquainted with the basic features of the site.</p>
<p><a href="/change">See recent changes</a></p>
    </div>
<hr>
    <div class="info"><img src="/img/change.png" align="left">
    <h3>NEWS</h3>
    <h4> Revised</h4>
    <ol>
        <li>You can create methods for another projects.</li>
        <li>Improved site structure.</li>
        <li>Improved methods of adding.</li>
    </ol>
        </div>
<hr>
</div>