<img src="/img/warning.png" align="left">
<H1>ОБНОВЛЕНИЯ НА СЕРВЕРЕ!</H1>
<a href="http://help-api.vallverk.com/img/handyBoyDB.png">Изменена схема базы данных!</a>
<h2>Обновлены методы</h2>
<ol>
    <li> Метод <a href="http://help-api.vallverk.com/method/detail/id/13">
                добавления нового сервиса</a>. Изменены входные данные и работа метода.
        После добавления нового сервиса необходимо
        <a href="http://help-api.vallverk.com/method/detail/id/36">добавить связь</a> "Сервер - тип работы"
    </li>
    <li> Метод <a href="http://help-api.vallverk.com/method/detail/id/24">
            Вывода списка работ</a>. Изменены данные на выходе. (добавлен вывод аддонов).
    </li>
    <li> Метод <a href="http://help-api.vallverk.com/method/detail/id/25">
            Вывод работы по id</a>. Изменены данные на выходе. (добавлен вывод аддонов).
    </li>
  </ol>
<h2>Добавлены методы</h2>
<ol>
    <li>Метод <a href="http://help-api.vallverk.com/method/detail/id/36">
            добавления связи </a> "Сервер - Тип работы".  </li>
    <li>Метод <a href="http://help-api.vallverk.com/method/detail/id/37">
            вывода списка работ  </a>по конкретному серверу</li>
    <li>Метод <a href="http://help-api.vallverk.com/method/detail/id/38">
            вывод списка аддонов </a>по конкретному сервису и работе</li>
    <li>Метод <a href="http://help-api.vallverk.com/method/detail/id/39">
            вывод списка всех аддонов</a>.</li>
    <li>Метод <a href="http://help-api.vallverk.com/method/detail/id/39">
            вывод списка аддонов</a> по конкретной работе.</li>

</ol>
<p>
    <h2>Изменения в базе данных</h2>
    Добавлены картинки в виде поле icon в typejob {"A":"/uploads/icon/hand_A.png","NA":"/uploads/icon/hand_NA.png"}
</p>

<a href="http://help-api.vallverk.com/help/error"><h3>Сообщить об ошибке </h3></a>
<a href="http://help-api.vallverk.com/request/add"><h3>Запросить метод</h3></a>