<legend>Reports</legend>
<table class="table table-bordered table-hover table-condensed">
    <tr>
        <th>User</th>
        <th>Capture</th>
        <th>Description</th>
        <th>Date</th>
        <th>Status</th>
    </tr>

    <?php
    foreach($this->error as $error)
    {
        echo '<tr><td>'.$error['username'].'</td>';
        echo '<td>'.$error['capture'].'</td>';
        echo '<td>'.$error['description'].'</td>';
        echo '<td>'.date("H:i:s d-m-Y",$error['date']).'</td>';
        echo '<td>';
        if($error['status']==0){ echo '<a href="/help/errorstatus/id/'.$error['id'].'"><i class="icon-exclamation-sign"></i></a>';}
        else {echo '<i class="icon-ok"></i>';}
        echo '</td></tr>';
    }
    ?>
</table>