<legend>Basic features</legend>
<p>This reference site methods RESTful API.</p>
<ol>
    <li>Click on the <a href="/project/add">Projects -> Add project</a> on menu to add project.</li>
    <li>Click on the <a href="/project">Projects -> List of projects</a> on menu to see a list of project.</li>
    <li>Click on the <a href="/request/add">Methods -> Request methods</a> on menu to request methods what you need.</li>
    <li>Click on the <a href="/request/send">Methods -> Send request</a> on menu to send request.</li>
    <li>Click on the <a href="/request">Methods -> List of request methods</a> on menu to see list of request methods</li>
    <li>Click on the <a href="/help/error">Error -> Report an error</a> on menu to report an error.</li>
    <li>Click on the <a href="/help/error">Error -> List of reports</a> on menu to see list of reports.</li>
    </ol>