<legend>RESTful API Methods</legend>
<table class="table table-bordered table-hover table-condensed">
    <tr>
        <th>Resource</th>
        <th>Description</th>
    </tr>

    <?php
        foreach($this->methods as $methods)
        {
            echo '<tr><td><a href="method/id/'.$methods['id'].'">'.$methods['name'].'</a></td>';
            echo '<td>'.$methods['short'].'</td></tr>';
        }
    ?>
</table>