<?php
date_default_timezone_set('Europe/Kiev');
?>
<!DOCTYPE html>
<html>
<head>
    <title>Help</title>
    <meta charset="utf-8">
    <link href="/css/bootstrap.css" rel="stylesheet" media="screen">
    <link href="/css/style.css" rel="stylesheet" media="screen">
</head>
<body>

    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <div class="container">
                <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <!-- Be sure to leave the brand out there if you want it shown -->
                <a class="brand" href="#">Help API</a>

                <!-- Everything you want hidden at 940px or less, place within here -->
                <div class="nav-collapse">
                    <ul class="nav">
                        <li><a href="/">Home</a></li>
                        <<li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Admin functions<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/project/add"><i class="icon-plus"></i>  Add project</a></li>
                                <li><a href="/method/add"><i class="icon-plus"></i> Add method</a></li>
                                <li><a href="/request"> <i class="icon-list"></i> List of request methods</a></li>
                                <li><a href="/help/errorall#"> <i class="icon-list"></i> List of reports</a></li>
                                <li><a href="/user"><i class="icon-user"></i> List of users </a></li>

                            </ul>
                        </li>
                        <li><a href="/project">Projects</a></li>
                        <li><a href="/request/add">Request methods</a></li>
                        <li><a href="/help/error">Report an error</a></li>
                        <li><a href="/request/send">Send request</a></li>

                        <?php
                     	    // Применяем уже знакомый метод для проверки авторизации пользователя
                        if (Zend_Auth::getInstance()->hasIdentity()) {
                        $url = $this->url(array('controller'=>'user', 'action'=>'logout'));
	                     // если пользователь авторизирован, показываем ему кнопку "Выход"
	                    echo "<li><a href=\"{$url}\">Exit</a></li>";} else {?>
                        <li><a href="#registration"class="text-warning" role="button" class="text-warning" data-toggle="modal">Registration</a></li>
                        <?php }?>

                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">

    <?php if (Zend_Auth::getInstance()->hasIdentity()) {
        echo '<div class="pull-right">Hello user <b class="text-info">'.Zend_Auth::getInstance()->getIdentity()->username.'</b></div>';
    }?>

    <div class="row-fluid">
        <div class="span12 cont">



<?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>



    <!-- Modal -->
    <div class="modal hide " id="registration" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
        <form method="post" action="/user/registration" name="registration">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Registration</h3>
        </div>
        <div class="modal-body">
            <img align="right" src="/img/preferences-contact-list.png">
            <p><input type="text" placeholder="Username..." required="true" name="username"></p>
            <p><input type="text" placeholder="First name..." required="true" name="firstName"></p>
            <p><input type="text" placeholder="Last name..." required="true" name="lastName"></p>
            <p><input type="email" placeholder="Email..." required="true" name="email"></p>
            <p><input type="password" placeholder="Password..." required="true" name="password"></p>
            <p><input type="password" placeholder="Repeat password..." required="true" name="passwordRepeat"></p>
            <p><input type="text" placeholder="Avatar..." name="avatar"></p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <button class="btn btn-primary">Registration</button>
        </div>
        </form>
    </div>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>