<?php
date_default_timezone_set('Europe/Kiev');
?>
<!DOCTYPE html>
<html>
<head>
    <title>Help</title>
    <meta charset="utf-8">
    <link href="/css/bootstrap.css" rel="stylesheet" media="screen">
    <link href="/css/style.css" rel="stylesheet" media="screen">
</head>
<body>
<div class="container">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <!-- Be sure to leave the brand out there if you want it shown -->
                <a class="brand" href="#">Help API</a>

                <!-- Everything you want hidden at 940px or less, place within here -->
                <div class="nav-collapse">
                    <ul class="nav">
                        <li><a href="/help">Home</a></li>
                        <li><a href="/help/methods">Methods</a></li>
                        <li><a href="/help/request">Request methods</a></li>
                        <li><a href="/help/error">Report an error</a></li>
                        <li class="active"><a href="/help/sendrequest">Send request</a></li>
                        <?php
                     	    // Применяем уже знакомый метод для проверки авторизации пользователя
                        if (Zend_Auth::getInstance()->hasIdentity()) {
                        $url = $this->url(array('controller'=>'help', 'action'=>'logout'));
	                     // если пользователь авторизирован, показываем ему кнопку "Выход"
	                    echo "<li><a href=\"{$url}\">Exit</a></li>";}

	?>
                       <!-- <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Dropdown <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <ul class="nav nav-pills">
        <li><a href="/help/requestall">Request methods</a></li>
        </li>
        <li><a href="/help/errorall#">Reports</a></li>
    </ul>
    <?php if (Zend_Auth::getInstance()->hasIdentity()) {
        echo '<div class="pull-right">Hello user <b class="text-info">'.Zend_Auth::getInstance()->getIdentity()->username.'</b></div>';
    }?>
    <div class="row-fluid">
        <div class="span12 cont">



<?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>