<?php
$this->title = "Delete method";
$this->headTitle($this->title);
?>
<p>Are you sure method
    '<?php echo $this->escape($this->method['name']); ?>'?
</p>

<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->method['id']; ?>"/>
        <input type="submit" class="btn" name="del" value="Yes"/>
        <input type="submit" class="btn btn-primary" name="del" value="No"/>
    </div>
</form>
