<legend><?=$this->method['name'];?></legend>
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="/">Methods</a> <span class="divider">/</span></li>
    <li class="active"><?=$this->method['name'];?></li>
</ul>

<h4>Description</h4>
<p class="text-info"><?=$this->method['short'];?></p>
<div class="well"><?=$this->method['description'];?></div>
<hr>
<b class="text-success">SUCCESS</b>
<div class="well"><?=$this->method['success'];?></div>
<hr>
<p><b class="text-error">ERROR</b></p>
<?php foreach($this->methoderror as $methoderror){ ?>
    <div class="pull-right">
    <a href="/method/erroredit/id/<?=$methoderror['id'];?>"><i class="icon-pencil"></i></a>
    <a href="/method/errordelete/id/<?=$methoderror['id'];?>"><i class="icon-remove"></i></a>
        </div>
<p><b><?=$methoderror['name'];?></b></p>
<div class="well"><?=$methoderror['description'];?></div>
<p><?=$methoderror['body'];?></p>
<?php }?>
<hr>
<h4>Data</h4>
<div class="well"><?=$this->method['data'];?></div>
<hr>
<ul class="nav nav-pills">
    <li><a href="/method/error/methodId/<?=$this->method['id'];?>">Add error</a> </li>
    <li class="disabled"><a href="#">Add parameters(In development)</a></li>
</ul>