<legend>Methods for project <span class="text-info"><?=$this->project['name']?></span></legend>
<table class="table table-bordered table-hover table-condensed">

  <thead>  <tr>
        <th>Resource</th>
        <th>Description</th>
        <th></th>
        <th></th>
    </tr>
  </thead>
    <tbody>
    <?php
    foreach($this->methods as $methods)
    { ?>
        <tr><td><a href="/method/detail/id/<?=$methods['id']?>"><?=$methods['name']?></a></td>
        <td><?=$methods['short']?></td>
            <?php  if (Zend_Auth::getInstance()->getIdentity()->role == 'admin'){ ?>
            <td><a href="/method/edit/id/<?=$methods['id']?>"><i class="icon-pencil"></i></a></td>';
        <td><a href="/method/delete/id/<?=$methods['id']?>"><i class="icon-remove"></i></a></td></tr>';
    <?php } ?>
    <?php } ?>
    </tbody>
</table>