<legend><?= $this->project['name'];?></legend>
<ul class="breadcrumb">
    <li><a href="/project">Projects</a> <span class="divider">/</span></li>
    <li><a href="/project/detail/?id=<?=$this->project['id'];?>"><?=$this->project['name'];?></a> <span class="divider">/</span></li>
    <li>Tasker</li>

</ul>
<ul id="sortable" class="nav nav-pills nav-stacked"
    data-project="<?=$this->project['id'];?>"
    >
<?php if ($this->category) { ?>

        <?php foreach ($this->category as &$category) { ?>
            <li >
                <a href="/bugs/?projectId=<?=$this->project['id'];?>&categoryId=<?=$category['id'];?>">
                    <?=$category['name'];?>
                </a>
            </li>
        <?php } ?>

<?php } ?>
</ul>

<?php if ($this->category == 0)  {?>
    <div class="alert alert-block alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4>Attention!</h4>
        None Categories!
    </div>

<?php } ?>

<hr>
<textarea id="category-text" data-project="<?= $this->project['id'];?>">
</textarea>
<button id="add-category" class="btn btn-primary">Send</button>