<legend>Projects</legend>
<table class="table table-hover">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
    </tr>

<?php
    foreach($this->project as $project)
    { ?>
        <tr><td><a href="/project/detail/?id=<?=$project['id'];?>"><?=$project['name']?></a></td>
        <td><?=$project['description']?></td>
            <?php  if (Zend_Auth::getInstance()->getIdentity()->role == 'admin'){ ?>
        <td><a href="/project/edit/id/<?=$project['id']?>"><i class="icon-pencil"></i></a></td>
        <td><a href="/project/delete/id/<?=$project['id']?>"><i class="icon-remove"></i></a></td></tr>
   <?php }?>
   <?php }?>
    </table>